In [ ]:
#default_exp sample
from nbdev.showdoc import show_doc

# Sample Notebook


In [ ]:
import numpy as np
import pandas as pd

In [ ]:
ones = np.identity(4)
print(ones)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
